# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chimney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chimney
  pod 'Firebase/Core'

  target 'chimneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chimneyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
