# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'chimney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chimney
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # Pods for address and site using Google Map API
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  # Pod for autoformatting a phone number kit
  pod 'PhoneNumberKit', '~> 2.6'

  target 'chimneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chimneyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
